# HOW TO BUILD STABLE:
# docker compose -f ./docker-compose.yml build --compress --parallel flutter-stable \
#   && docker compose -f ./docker-compose.yml build --compress --parallel flutter-stable-web flutter-stable-android
#
# HOW TO BUILD BETA:
# docker compose -f ./docker-compose.yml build --compress --parallel flutter-beta \
#   && docker compose -f ./docker-compose.yml build --compress --parallel flutter-beta-web flutter-beta-android
#
# HOW TO BUILD MASTER:
# docker compose -f ./docker-compose.yml build --compress --parallel flutter-master \
#   && docker compose -f ./docker-compose.yml build --compress --parallel flutter-master-web flutter-master-android
#
# HOW TO BUILD AND PUSH ALL:
# docker compose -f ./docker-compose.yml build --compress --parallel \
#     flutter-stable flutter-beta flutter-master \
#   && docker compose -f ./docker-compose.yml build --compress --parallel \
#     flutter-stable-web flutter-stable-android flutter-beta-web flutter-beta-android flutter-master-web flutter-master-android \
#   && docker compose push

version: "3.9"

services:

  #############################################################
  # STABLE

  flutter-stable:
    image: plugfox/flutter:stable
    build:
      dockerfile: dockerfiles/flutter.dockerfile
      context: .
      args:
        - VERSION=stable

  flutter-stable-web:
    image: plugfox/flutter:stable-web
    build:
      dockerfile: flutter_web.dockerfile
      context: .
      args:
        - VERSION=stable
