name: tg_miniapp_ui
description: Flutter ui kit for tapps
version: 0.1.0+1


environment:
  sdk: "^3.3.0"

dependencies: 
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
